### ISSUE TITLE
Create oasis-node docker image in oasis-runtime

### ISSUE THREAD

**Issue by ptrus** [oasislabs/oasis-runtime#937]
Currently we build the base node docker image in https://github.com/oasislabs/oasis-core That image is not used anywhere but for building the testnet image in this repo. 

Instead we could build the image from scratch in this repository. Should also simplify versioning as we would track node version via cargo.lock instead of two places as we do currently (cargo.lock and separate docker tag tracking)

**Comment by ptrus** [comment]
Alternatively we could:
- build the oasis-core docker image on every master merge and tag it with commit hash (and remove the whole "promote" step in that repo)
- in oasis-runtime we build the image based the oasis-core image (same as we do now), tagged with the commit specified in the Cargo.lock file (would probably require some manual parsing of the Cargo.lock file to extract the commit sha)

**Comment by vege10** [comment]
Hi There,
Would someone able to help me up?
My docker container are all up, just that my internal samson process keep on restarting.
It doesn't allowed me to stop or start it.

Enclosed herewith my docker logs:-
[omndocker@stelivomr03 ~]$ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                                                                            NAMES
6bee7c1f58c9        omn/traffic-control:v1.07.20   "/tc.sh run -cont_..."   11 months ago       Up About an hour    10.184.78.213:25->25/tcp, 10.184.78.213:2222->2222/tcp, 10.184.78.213:2525->2525/tcp, 10.184.78.213:2775->2775/tcp, 10.184.78.213:8888->8888/tcp, 10.184.78.213:29997->29997/tcp, 10.184.78.213:5060->5060/udp   0-5c98ae74
c7c4a50250b9        omn/traffic-control:v1.07.20   "/tc.sh run -cont_..."   11 months ago       Up About an hour                                                                                                                                                                                                                     9-5c93bbee
e7c050a92b46        omn/traffic-control:v1.07.20   "/tc.sh run -cont_..."   11 months ago       Up About an hour                                                                                                                                                                                                                     1-5c939368
5be022c00512        omn/traffic-control:v1.07.20   "/tc.sh run -cont_..."   11 months ago       Up About an hour                                                                                                                                                                                                                     2-5c927558
[omndocker@stelivomr03 ~]$ dso 0-5c98ae74
Last login: Fri Mar  6 18:13:54 +08 2020 on console
# 0-5c98ae74 (OASIS) ~$ sci -list
Cannot open '.samson.port'
Make sure you are in the sysdir and that samson is running
# 0-5c98ae74 (OASIS) ~$ sci -list
          personality.sh  [Running]
               pfwdog.sh  [Running]
                splinter  [Running(mondo)]
              cvp_server  [Running(mondo)]
             clam_server  [Running(mondo)]
              dgi_server  [Stopped]
                 clogger  [Stopped]
             sbug_server  [Stopped]
            cconf_server  [Stopped]
            cstat_server  [Stopped]
               cstat_agg  [Stopped]
               pstat_svr  [Stopped]
                  beagle  [Stopped]
              dsm_server  [Stopped]
              dfl_server  [Stopped]
         moshazelcast.sh  [Stopped]
         moscassandra.sh  [Stopped]
                   n4rtr  [Stopped]
                    kylo  [Stopped]
                snmpd.sh  [Stopped]
            cconf_logger  [Stopped]
                     sca  [Stopped]
              dns_server  [Stopped]
                 simpson  [Stopped]
                  roosta  [Stopped]
                   helga  [Stopped]
     crb_bus_logic_vld8r  [Stopped]
                     dec  [Stopped]
                    shep  [Stopped]
              tron_vld8r  [Stopped]
              vantrix.sh  [Stopped]
                 wassail  [Stopped]
          tc_cconf_vld8r  [Stopped]
               tomcat.sh  [Stopped]
              haproxy.sh  [Stopped]
                nginx.sh  [Stopped]
                  dcm.sh  [Stopped]
            gandhi_store  [Stopped]
             delilah4sam  [Stopped]
# 0-5c98ae74 (OASIS) ~$ sci -stop
Ok
# 0-5c98ae74 (OASIS) ~$ sci -list
Cannot open '.samson.port'
Make sure you are in the sysdir and that samson is running
# 0-5c98ae74 (OASIS) ~$ sci -list
          personality.sh  [Running]
               pfwdog.sh  [Running]
                splinter  [Running(mondo)]
              cvp_server  [Running(mondo)]
             clam_server  [Running(mondo)]
              dgi_server  [Stopped]
                 clogger  [Stopped]
             sbug_server  [Stopped]
            cconf_server  [Stopped]
            cstat_server  [Stopped]
               cstat_agg  [Stopped]
               pstat_svr  [Stopped]
                  beagle  [Stopped]
              dsm_server  [Stopped]
              dfl_server  [Stopped]
         moshazelcast.sh  [Stopped]
         moscassandra.sh  [Stopped]
                   n4rtr  [Stopped]
                    kylo  [Stopped]
                snmpd.sh  [Stopped]
            cconf_logger  [Stopped]
                     sca  [Stopped]
              dns_server  [Stopped]
                 simpson  [Stopped]
                  roosta  [Stopped]
                   helga  [Stopped]
     crb_bus_logic_vld8r  [Stopped]
                     dec  [Stopped]
                    shep  [Stopped]
              tron_vld8r  [Stopped]
              vantrix.sh  [Stopped]
                 wassail  [Stopped]
          tc_cconf_vld8r  [Stopped]
               tomcat.sh  [Stopped]
              haproxy.sh  [Stopped]
                nginx.sh  [Stopped]
                  dcm.sh  [Stopped]
            gandhi_store  [Stopped]
             delilah4sam  [Stopped]
# 0-5c98ae74 (OASIS) ~$
