### ISSUE TITLE
Bump latest oasis-core-* packages

### ISSUE THREAD

**Issue by matevz** [oasislabs/oasis-runtime#962]
Currently, doing 
```
cd oasis-runtime
cargo update -p oasis-core-runtime
cargo update -p oasis-core-client
cargo update -p oasis-core-keymanager-api
```

and then compiling will fail in number of places (the missing `Apply` call in `genesis`, `query_block` rename in `gateway` modules, maybe somewhere else). Fix the compatibility issues so that it compiles again with the latest versions of the `oasis-core-*` packages.

**Comment by samohyes** [comment]
So when will the problem be solved? The repo hasn't been updated for a month.
